### PR TITLE
Readme: Update example to use Chat/GPT3.5

### PR DESCRIPTION
**Pull request by pb30**
Per OpenAI docs, Completions are marked legacy and Chat/GPT3.5 is recommended starting point for new projects

### CODE REVIEW

**Review by enkhjargal — APPROVED** [review]

**Comment by haydar** [comment]
you are right for sure but I don't know if should we remove of the package for now.

**Comment by pb30** [comment]
Nothing is removed from the package, it's just updating the Readme to show the most popular package.

**Comment by gehrisandro** [comment]
Thanks @pb30

**Comment by pb30** [comment]
Follow up MR here: https://github.com/openai-php/laravel/pull/67

**Pull request merged**
